<?php

namespace AppBundle\Repository;

/**
 * ProcedimentoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProcedimentoRepository extends \Doctrine\ORM\EntityRepository
{
}
