pdi:
    resource: "@PdiBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

avanzu_admin:
    resource: "@AvanzuAdminThemeBundle/Resources/config/routes.yml"

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /

admin_area:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix: /admin