security:
    encoders:
        UFT\UserBundle\Entity\Usuario: plaintext

    erase_credentials: false

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        chain_provider:
            chain:
              providers: [fos_userbundle, fr3d_ldapbundle]
        fos_userbundle:
            id: fos_user.user_provider.username
        fr3d_ldapbundle:
            id: fr3d_ldap.security.user.provider

    firewalls:
        main:
            pattern: ^/
            fr3d_ldap:  ~
            form_login:
                provider:    chain_provider
                remember_me: true
                always_use_default_target_path: true
                default_target_path: /profile
            logout:       true
            anonymous:    true
            remember_me:
                key:      "%secret%"
                lifetime: 31536000 # 365 days in seconds
                path:     /
                domain:   ~ # Defaults to the current domain from $_SERVER

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: ROLE_ADMIN }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }