services:
#    pdi.example:
#        class: UFT\PdiBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    pdi.admin.pdi:
        class: UFT\PdiBundle\Admin\PDIAdmin
        arguments: [~, UFT\PdiBundle\Entity\PDI, PdiBundle:PDIAdmin]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: PDI, label_translator_strategy: sonata.admin.label.strategy.noop }
        public: true
