workflow:
    workflows:
        tarefa:
            type: 'workflow'
            marking_store:
                type: 'multiple_state' # or 'single_state'
                arguments:
                    - 'stateTarefa'
            supports:
                - UFT\PdiBundle\Entity\Tarefa
            places:
                - tarefa_criada
                - pdi_aberto
                - tarefa_null
                - tarefa_aprovada
                - tarefa_ug
                - tarefa_revisada
                - tarefa_concluida
            transitions:
                # Isso será criado automativamente via command, será uma cópia do PDI do ano anterior com o status pdi_aberto
                tarefa_criar:
                    from: [tarefa_null,pdi_aberto]
                    to: tarefa_criada
                tarefa_encaminhar_ug:
                    from: tarefa_criada
                    to: tarefa_ug
                tarefa_aprovar:
                    from: tarefa_ug
                    to: [tarefa_aprovada,tarefa_revisada]
                tarefa_finalizar:
                    from: [tarefa_aprovada,tarefa_revisada]
                    to: tarefa_concluida
        pdi:
            type: 'workflow'
            marking_store:
                type: 'multiple_state' # or 'single_state'
                arguments:
                    - 'statePdi'
            supports:
                - UFT\PdiBundle\Entity\Tarefa
            places:
                - pdi_aberto
                - tarefa_criada
                - tarefa_aprovada
                - tarefa_ug
                - tarefa_revisada
                - tarefa_concluida
            transitions:
                # Isso será criado automativamente via command, será uma cópia do PDI do ano anterior com o status pdi_aberto
                tarefa_criar:
                    from: pdi_aberto
                    to: tarefa_criada
                tarefa_encaminhar_ug:
                    from: tarefa_criada
                    to: tarefa_ug
                tarefa_aprovar:
                    from: tarefa_ug
                    to: [tarefa_aprovada,tarefa_revisada]
                tarefa_finalizar:
                    from: [tarefa_aprovada,tarefa_revisada]
                    to: tarefa_concluida