<?php

namespace UFT\PdiBundle\Repository;

/**
 * PDIRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PDIRepository extends \Doctrine\ORM\EntityRepository
{
}
