<?php

namespace UFT\PdiBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TarefaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TarefaRepository extends EntityRepository
{
}
