user_homepage:
    path:     /user/{name}
    defaults: { _controller: UserBundle:Default:index }

gpu_users_list:
    path:     /admin/users/list
    defaults: { _controller: UserBundle:Default:listUser }

gpu_user_edit:
    path:     /admin/users/edit/{id}
    defaults: { _controller: UserBundle:Default:editUsers }