services:
#    user.example:
#        class: UFT\UserBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    uft_user.ldap.user_hydrator:
        class: UFT\UserBundle\Util\Ldap\UserHydrator
        arguments: ["@service_container"]
    uft_user.fos.user_manager:
        class: UFT\UserBundle\Util\FOS\UserManager
        arguments: ["@security.encoder_factory","@fos_user.util.username_canonicalizer","@fos_user.util.email_canonicalizer","@fos_user.entity_manager","%fos_user.model.user.class%","@security.acl.provider"]